bashrc: add vault-list-keys helper

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -48,6 +48,23 @@ function git_alias() {
   fi
 }
 
+function vault-list-keys() {
+  local repo="$1"
+  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    repo=$(
+      echo "$(git config --get remote.origin.url)" \
+        | sed -E 's#\.git$##' \
+        | sed -E 's#^.*[:/]([^/]+/[^/]+)$#\1#'
+    )
+  else
+    echo "Error: not in a git repo and no path supplied" >&2
+    return 1
+  fi
+  (set -x;
+    vault kv get -format=json "forgejo-runner/$repo"
+  ) | jq '.data.data|keys'
+}
+
 # ----[ general aliases ]-------------------------------------
 alias \
   clear="tput -T xterm reset" \
